// Code generated by go-bindata.
// sources:
// assets/fonts/exo2-bold.ttf
// assets/fonts/exo2-regular.ttf
// assets/fonts/fontawesome-webfont.eot
// assets/fonts/fontawesome-webfont.svg
// assets/fonts/fontawesome-webfont.ttf
// assets/fonts/fontawesome-webfont.woff
// assets/fonts/fontawesome-webfont.woff2
// assets/images/favicon.ico
// assets/javascripts/bootstrap.min.js
// assets/javascripts/mithril.min.js
// assets/javascripts/mithril.min.js.map
// assets/stylesheets/animate.min.css
// assets/stylesheets/bootstrap.min.css
// assets/stylesheets/bootstrap.min.css.map
// assets/stylesheets/font-awesome.min.css
// assets/stylesheets/style.css
// lib/views/layout.ace
// lib/views/top/index.ace
// DO NOT EDIT!

package main

import (
	"net/http"
	"fmt"
	"io/ioutil"
	"strings"
	"os"
	"path/filepath"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// assetsFontsExo2BoldTtf reads file data from disk. It returns an error on failure.
func assetsFontsExo2BoldTtf() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/fonts/exo2-bold.ttf"
	name := "assets/fonts/exo2-bold.ttf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsFontsExo2RegularTtf reads file data from disk. It returns an error on failure.
func assetsFontsExo2RegularTtf() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/fonts/exo2-regular.ttf"
	name := "assets/fonts/exo2-regular.ttf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsFontsFontawesomeWebfontEot reads file data from disk. It returns an error on failure.
func assetsFontsFontawesomeWebfontEot() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/fonts/fontawesome-webfont.eot"
	name := "assets/fonts/fontawesome-webfont.eot"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsFontsFontawesomeWebfontSvg reads file data from disk. It returns an error on failure.
func assetsFontsFontawesomeWebfontSvg() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/fonts/fontawesome-webfont.svg"
	name := "assets/fonts/fontawesome-webfont.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsFontsFontawesomeWebfontTtf reads file data from disk. It returns an error on failure.
func assetsFontsFontawesomeWebfontTtf() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/fonts/fontawesome-webfont.ttf"
	name := "assets/fonts/fontawesome-webfont.ttf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsFontsFontawesomeWebfontWoff reads file data from disk. It returns an error on failure.
func assetsFontsFontawesomeWebfontWoff() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/fonts/fontawesome-webfont.woff"
	name := "assets/fonts/fontawesome-webfont.woff"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsFontsFontawesomeWebfontWoff2 reads file data from disk. It returns an error on failure.
func assetsFontsFontawesomeWebfontWoff2() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/fonts/fontawesome-webfont.woff2"
	name := "assets/fonts/fontawesome-webfont.woff2"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsImagesFaviconIco reads file data from disk. It returns an error on failure.
func assetsImagesFaviconIco() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/images/favicon.ico"
	name := "assets/images/favicon.ico"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsJavascriptsBootstrapMinJs reads file data from disk. It returns an error on failure.
func assetsJavascriptsBootstrapMinJs() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/javascripts/bootstrap.min.js"
	name := "assets/javascripts/bootstrap.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsJavascriptsMithrilMinJs reads file data from disk. It returns an error on failure.
func assetsJavascriptsMithrilMinJs() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/javascripts/mithril.min.js"
	name := "assets/javascripts/mithril.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsJavascriptsMithrilMinJsMap reads file data from disk. It returns an error on failure.
func assetsJavascriptsMithrilMinJsMap() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/javascripts/mithril.min.js.map"
	name := "assets/javascripts/mithril.min.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsStylesheetsAnimateMinCss reads file data from disk. It returns an error on failure.
func assetsStylesheetsAnimateMinCss() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/stylesheets/animate.min.css"
	name := "assets/stylesheets/animate.min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsStylesheetsBootstrapMinCss reads file data from disk. It returns an error on failure.
func assetsStylesheetsBootstrapMinCss() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/stylesheets/bootstrap.min.css"
	name := "assets/stylesheets/bootstrap.min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsStylesheetsBootstrapMinCssMap reads file data from disk. It returns an error on failure.
func assetsStylesheetsBootstrapMinCssMap() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/stylesheets/bootstrap.min.css.map"
	name := "assets/stylesheets/bootstrap.min.css.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsStylesheetsFontAwesomeMinCss reads file data from disk. It returns an error on failure.
func assetsStylesheetsFontAwesomeMinCss() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/stylesheets/font-awesome.min.css"
	name := "assets/stylesheets/font-awesome.min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetsStylesheetsStyleCss reads file data from disk. It returns an error on failure.
func assetsStylesheetsStyleCss() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/assets/stylesheets/style.css"
	name := "assets/stylesheets/style.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// libViewsLayoutAce reads file data from disk. It returns an error on failure.
func libViewsLayoutAce() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/lib/views/layout.ace"
	name := "lib/views/layout.ace"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// libViewsTopIndexAce reads file data from disk. It returns an error on failure.
func libViewsTopIndexAce() (*asset, error) {
	path := "/home/hiconyan/src/mouryou-web/lib/views/top/index.ace"
	name := "lib/views/top/index.ace"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if (err != nil) {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"assets/fonts/exo2-bold.ttf": assetsFontsExo2BoldTtf,
	"assets/fonts/exo2-regular.ttf": assetsFontsExo2RegularTtf,
	"assets/fonts/fontawesome-webfont.eot": assetsFontsFontawesomeWebfontEot,
	"assets/fonts/fontawesome-webfont.svg": assetsFontsFontawesomeWebfontSvg,
	"assets/fonts/fontawesome-webfont.ttf": assetsFontsFontawesomeWebfontTtf,
	"assets/fonts/fontawesome-webfont.woff": assetsFontsFontawesomeWebfontWoff,
	"assets/fonts/fontawesome-webfont.woff2": assetsFontsFontawesomeWebfontWoff2,
	"assets/images/favicon.ico": assetsImagesFaviconIco,
	"assets/javascripts/bootstrap.min.js": assetsJavascriptsBootstrapMinJs,
	"assets/javascripts/mithril.min.js": assetsJavascriptsMithrilMinJs,
	"assets/javascripts/mithril.min.js.map": assetsJavascriptsMithrilMinJsMap,
	"assets/stylesheets/animate.min.css": assetsStylesheetsAnimateMinCss,
	"assets/stylesheets/bootstrap.min.css": assetsStylesheetsBootstrapMinCss,
	"assets/stylesheets/bootstrap.min.css.map": assetsStylesheetsBootstrapMinCssMap,
	"assets/stylesheets/font-awesome.min.css": assetsStylesheetsFontAwesomeMinCss,
	"assets/stylesheets/style.css": assetsStylesheetsStyleCss,
	"lib/views/layout.ace": libViewsLayoutAce,
	"lib/views/top/index.ace": libViewsTopIndexAce,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"assets": &bintree{nil, map[string]*bintree{
		"fonts": &bintree{nil, map[string]*bintree{
			"exo2-bold.ttf": &bintree{assetsFontsExo2BoldTtf, map[string]*bintree{
			}},
			"exo2-regular.ttf": &bintree{assetsFontsExo2RegularTtf, map[string]*bintree{
			}},
			"fontawesome-webfont.eot": &bintree{assetsFontsFontawesomeWebfontEot, map[string]*bintree{
			}},
			"fontawesome-webfont.svg": &bintree{assetsFontsFontawesomeWebfontSvg, map[string]*bintree{
			}},
			"fontawesome-webfont.ttf": &bintree{assetsFontsFontawesomeWebfontTtf, map[string]*bintree{
			}},
			"fontawesome-webfont.woff": &bintree{assetsFontsFontawesomeWebfontWoff, map[string]*bintree{
			}},
			"fontawesome-webfont.woff2": &bintree{assetsFontsFontawesomeWebfontWoff2, map[string]*bintree{
			}},
		}},
		"images": &bintree{nil, map[string]*bintree{
			"favicon.ico": &bintree{assetsImagesFaviconIco, map[string]*bintree{
			}},
		}},
		"javascripts": &bintree{nil, map[string]*bintree{
			"bootstrap.min.js": &bintree{assetsJavascriptsBootstrapMinJs, map[string]*bintree{
			}},
			"mithril.min.js": &bintree{assetsJavascriptsMithrilMinJs, map[string]*bintree{
			}},
			"mithril.min.js.map": &bintree{assetsJavascriptsMithrilMinJsMap, map[string]*bintree{
			}},
		}},
		"stylesheets": &bintree{nil, map[string]*bintree{
			"animate.min.css": &bintree{assetsStylesheetsAnimateMinCss, map[string]*bintree{
			}},
			"bootstrap.min.css": &bintree{assetsStylesheetsBootstrapMinCss, map[string]*bintree{
			}},
			"bootstrap.min.css.map": &bintree{assetsStylesheetsBootstrapMinCssMap, map[string]*bintree{
			}},
			"font-awesome.min.css": &bintree{assetsStylesheetsFontAwesomeMinCss, map[string]*bintree{
			}},
			"style.css": &bintree{assetsStylesheetsStyleCss, map[string]*bintree{
			}},
		}},
	}},
	"lib": &bintree{nil, map[string]*bintree{
		"views": &bintree{nil, map[string]*bintree{
			"layout.ace": &bintree{libViewsLayoutAce, map[string]*bintree{
			}},
			"top": &bintree{nil, map[string]*bintree{
				"index.ace": &bintree{libViewsTopIndexAce, map[string]*bintree{
				}},
			}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
        data, err := Asset(name)
        if err != nil {
                return err
        }
        info, err := AssetInfo(name)
        if err != nil {
                return err
        }
        err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
        if err != nil {
                return err
        }
        err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
        if err != nil {
                return err
        }
        err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
        if err != nil {
                return err
        }
        return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
        children, err := AssetDir(name)
        // File
        if err != nil {
                return RestoreAsset(dir, name)
        }
        // Dir
        for _, child := range children {
                err = RestoreAssets(dir, filepath.Join(name, child))
                if err != nil {
                        return err
                }
        }
        return nil
}

func _filePath(dir, name string) string {
        cannonicalName := strings.Replace(name, "\\", "/", -1)
        return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}


func assetFS() http.FileSystem {
	for k := range _bintree.Children {
		return http.Dir(k)
	}
	panic("unreachable")
}
